### ISSUE TITLE
Any plans to publish source code for training?

### ISSUE THREAD

**Issue by luopeixiang** [tzm-tora/Learning-based-synthtext-engine#2]
I came across your paper and I'm really impressed with your work. I noticed that you haven't published the training code and was wondering if you have any plans to do so in the future.

**Comment by tzm-tora** [comment]
Hi, thanks for your interest in our work.
We do have the plan to release the training code and models, but this paper is under review now, and we will release the code and models according to the review process and result.
Our dataset has been released in the following link, please use it if you are also interested in.
https://github.com/iiclab/DecompST

**Comment by tzm-tora** [comment]
The training code and inference code are released.
